apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-demand-api
  labels:
    app: retail-demand-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: retail-demand-api

  template:
    metadata:
      labels:
        app: retail-demand-api

    spec:
      containers:
        - name: api

          image: retail-demand-api:5.6
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          env:
            - name: MODEL_SOURCE
              value: "packaged"

            - name: PACKAGED_MODEL_PATH
              value: "/app/exported_model"

            - name: PACKAGED_MODEL_VERSION
              value: "7"

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"