apiVersion: v1
kind: Service
metadata:
  name: retail-demand-api
  labels:
    app: retail-demand-api
spec:
  type: NodePort

  selector:
    app: retail-demand-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
      protocol: TCP