FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.lock.txt .
# depen
RUN pip install --no-cache-dir -r requirements.lock.txt

# Copy application code
COPY src/ src/

# Copy processed data (feature template, etc.)
COPY data/ data/

# 🔥 COPY THE EXPORTED MODEL (THIS WAS MISSING)
COPY exported_model/ model/

# Expose port
EXPOSE 8000

# Start FastAPI
CMD ["uvicorn", "src.serving.app:app", "--host", "0.0.0.0", "--port", "8000"]